Majsans viewportbranch
WeatherMagic/weather-front pull request #25
Opened 2016-11-07 15:01 UTC by majil334

Aspect ratio fungerar nu.

Testa genom att ändra storlek och ratio på fönstret, jordgloben ska alltid vara sfärisk

2016-11-08 12:57 UTC, Rovanion requested changes

2016-11-08 12:57 UTC, Rovanion commented on resources/public/css/style.css
> -}
Varför tar du bort alla de här raderna?

2016-11-08 12:57 UTC, Rovanion commented on src/weather_magic/core.cljs
> +      (gl/set-viewport (:aspect @state/camera))
Det här funktionskallet vill vi inte göra varje frame utan bara när vi får ett resize-event.

2016-11-08 12:57 UTC, Rovanion commented on src/weather_magic/event_handlers.cljs
> +(defn resize-handler [event]
Eftersom vi inte länge använder event i den här funktionen, men en event handler måste per spec ta ett argument, så bör argumentet `event` döpas om till `_` per konvention: http://stackoverflow.com/questions/16020278/clojure-what-does-do-in-a-functions-argument-list

2016-11-08 12:57 UTC, Rovanion commented on src/weather_magic/state.cljs
> -;; The user camera into the world.
Ta inte bort den här kommentaren.

2016-11-08 15:21 UTC, MangeI89 requested changes

2016-11-08 15:21 UTC, MangeI89 commented on src/weather_magic/state.cljs
> +
Ta bort de fyra ovanstående raderna

2016-11-08 21:48 UTC, Rovanion approved these changes

2016-11-09 08:03 UTC, hansfilipelo commented
@MangeI89 Verkat som att allt som kvarstår här är att du godkänner förändringarna du efterfrågade och testar PR.

2016-11-09 10:30 UTC, MangeI89 approved these changes
Everything looks good

2016-11-09 10:30 UTC, merged