Temp texture
WeatherMagic/weather-front pull request #27
Opened 2016-11-09 21:50 UTC by MangeI89

La till en shader som visar temperatur interpolerad mellan rött och blått. Fixade även lite css

2016-11-14 14:15 UTC, majil334 reviewed
ta bort resources/public/img/world-temp.png-filen :)

2016-11-14 14:15 UTC, majil334 commented on src/weather_magic/shaders.cljs
> +(def blend-shader-spec
använd assoc-funktionen :)

2016-11-15 16:01 UTC, Rovanion requested changes
I stort: Jag ser ingen egentlig gulfärg i den producerade bilden utan bara blått och rött. Ska det vara så?

Den behöver fixen i PR #28 för att bli av med WebGL-varningar på min maskin.

Stilförändringarna som är inkluderade i den här PR:en borde varit i en separat branch som vi lätt skulle kunnat merge:a oberoende från resterande kod i denna PR. Nu blir det väldigt kod att granska på en gång  och det blir jobbigt att uppdatera den här mot master om den förändras under tiden PR:en ligger uppe.

2016-11-15 16:01 UTC, Rovanion commented on src/weather_magic/state.cljs
> +(defonce b2 (atom "top"))
Byt namn på b1 och b2 till någonting som säger vad atomerna innehåller. Använd nyckelord istället för strängar om innehållet är någonting som ska läsas av programmet.

2016-11-15 16:01 UTC, Rovanion commented on src/weather_magic/state.cljs
> +                                               :fov    110
Vad motiverar denna ändring?

2016-11-15 16:01 UTC, Rovanion commented on resources/public/css/style.css
> +.button {
I `border-color: #255aaa` i den här regeln gör att knapparna blir genomskinliga i Firefox. Visserligen inte en del av koden som ändrades i den här PR:en men det behöver fixas i vilket fall.

2016-11-15 16:01 UTC, Rovanion commented on src/weather_magic/ui.cljs
> +  [:div {:id "data-layer-container" :class (@state/intro-visible {:hidden :visible :visible :hidden})}
Använd funktionen hide-unhide istället för att copy-paste:a koden.

2016-11-15 16:01 UTC, Rovanion commented on src/weather_magic/ui.cljs
> +  [:div {:id "view-selection-container" :class (@state/intro-visible {:hidden :visible :visible :hidden})}
Samma sak här: Använd funktionen hide-unhide istället för att copy-paste:a koden.

2016-11-15 16:01 UTC, Rovanion commented on src/weather_magic/ui.cljs
> +   [button "Drought" swap! state/data-layer-atom util/toggle :Drought]])
Vad motiverar ändringarna till raderna här ovan?

2016-11-15 16:01 UTC, Rovanion commented on src/weather_magic/util.cljs
> +  (swap! shader-selector (fn [] shader)))
Här vill du skriva `(reset! shader-selector shader)` istället.

2016-11-15 16:01 UTC, Rovanion commented on src/weather_magic/util.cljs
> +(defn switch-shader
Den här funktionen hör hemma i shaders.cljs

2016-11-15 17:52 UTC, MangeI89 commented on resources/public/css/style.css
> +.button {
Om det inte är en del av denna PR:en kan väl du i så fall skapa en branch och ordna det eftersom jag inte vet på rak arm hur jag ska göra.

2016-11-15 17:53 UTC, MangeI89 commented on src/weather_magic/ui.cljs
> +  [:div {:id "data-layer-container" :class (@state/intro-visible {:hidden :visible :visible :hidden})}
Eftersom vi vill ha inversen av state/introvisible kan jag inte använda hide-unhide

2016-11-16 10:41 UTC, yotomten commented on src/weather_magic/shaders.cljs
> +  (reset! shader-selector shader))
Shader-selector does not sound like the name of the current shader, more like a tool to select shader. Another name maybe?

2016-11-16 10:45 UTC, yotomten commented on src/weather_magic/shaders.cljs
> +  (reset! shader-selector shader))
current-shader?

2016-11-16 15:56 UTC, Rovanion commented on resources/public/css/style.css
> +.button {
Jag kan väl iofs hålla med om att buggar inte introducerade av en PR inte nödvändigtvis ska lösas i den PR:en. Men någonstans ska det väl lösas.

Just den här buggen löses genom att ta bort raden border-color: #255aaa från regeln.

2016-11-16 15:57 UTC, Rovanion commented on src/weather_magic/ui.cljs
> +  [:div {:id "data-layer-container" :class (@state/intro-visible {:hidden :visible :visible :hidden})}
Är det inte bara kalla `(hide-unhide @state/intro-visible)`?

2016-11-16 17:36 UTC, Rovanion approved these changes

2016-11-16 17:36 UTC, merged