Donald Trump now dominates the earth. Program modified to match reality.
WeatherMagic/weather-front pull request #28
Opened 2016-11-10 13:45 UTC by Rovanion

2016-11-14 14:27 UTC, majil334 commented
Haha, snyggt (och aktuellt). Du har en conflicting file så kan inte mergea

2016-11-16 10:00 UTC, MangeI89 commented on src/weather_magic/state.cljs
> +(defonce earth-animation-fn (atom nil))
Varför detta? Tycker att det är ett bra initialt tillstånd att jorden snurrar.

2016-11-16 10:01 UTC, MangeI89 commented on src/weather_magic/state.cljs
>                                                 :fov    90
Kanske vi borde introducerade samma namespace som i core dvs [thi.ng.geom.vector :as v :refer [vec2 vec3]]. Då behövs inte v/vec3 utan endast vec3.

2016-11-16 10:03 UTC, MangeI89 commented on src/weather_magic/core.cljs
>                :lightCol   [:vec3 [1 1 1]]
Vi borde ändra namnen på texturerna så att de är mer förklarande

2016-11-16 10:04 UTC, MangeI89 commented on src/weather_magic/core.cljs
>     :attribs  {:position :vec3
fade va väl bra för att testa att det funkar men onödigt nu

2016-11-16 10:04 UTC, MangeI89 commented on src/weather_magic/core.cljs
>        (gl/make-buffers-in-spec state/gl-ctx glc/static-draw)
Samma här, bra för test men onödigt att merga med master

2016-11-16 10:06 UTC, MangeI89 commented on src/weather_magic/state.cljs
samma här, bättre med vec3 än v/vec3

2016-11-16 10:07 UTC, MangeI89 commented on src/weather_magic/state.cljs
vore väl bra om vi har en initial textur

2016-11-16 10:12 UTC, MangeI89 commented on src/weather_magic/world.cljs
Bättre läsbarhet om vi skriver :translation (vec3 0 0 0)

2016-11-16 10:13 UTC, MangeI89 commented on src/weather_magic/world.cljs
Samma här, (vec3 0 0 0)

2016-11-16 10:13 UTC, MangeI89 requested changes
Se kommentarer

2016-11-16 11:47 UTC, Rovanion commented on src/weather_magic/state.cljs
> +(defonce earth-animation-fn (atom nil))
Yes, vi får ta ett samtal om det här och besluta om vi ska acceptera den här lösningen eller omorganisera vårat tillstånd så att det istället för att ligga i `state.cljs` ligger i de områdesspecifika filerna så som `models.cljs` och `textures.cljs`.

Problemet vi går in i annars är cirkulärberoenden där funktionerna i `world.cljs` modifierar det modifierbara tillståndet i `state.cljs` samtidigt som man i `state.cljs` vill sätta defaultvärden för atomerna från `world.cljs`.

2016-11-16 11:53 UTC, Rovanion commented on src/weather_magic/state.cljs
>                                                 :fov    90
Naturligtvis en smaksak. Men jag genomför ändringen.

2016-11-16 12:26 UTC, Rovanion commented on src/weather_magic/core.cljs
>                :lightCol   [:vec3 [1 1 1]]
Passar namnen :base och :trump? För base byter vi ut allt eftersom medans trumptexten ligger som ett överlag på båda.

2016-11-16 12:30 UTC, Rovanion commented on src/weather_magic/core.cljs
>     :attribs  {:position :vec3
Faden är borttagen.

2016-11-16 12:31 UTC, Rovanion commented on src/weather_magic/state.cljs
Samma problem som den andra nil:en jag introducerade. Texturen sätts just nu i `textures.cljs`.

2016-11-16 12:32 UTC, Rovanion commented on src/weather_magic/state.cljs
Ordnat.

2016-11-16 12:34 UTC, Rovanion commented on src/weather_magic/world.cljs
Done

2016-11-16 12:34 UTC, Rovanion commented on src/weather_magic/world.cljs
And done.

2016-11-16 14:43 UTC, MangeI89 commented on src/weather_magic/shaders.cljs
>     }")
Nu är jag ett rövhål men vi kan ta bort .rgba helt.

2016-11-16 15:10 UTC, MangeI89 approved these changes

2016-11-16 15:11 UTC, merged