Multiple objects
WeatherMagic/weather-front pull request #29
Opened 2016-11-15 10:21 UTC by MangeI89

Added another canvas which shows the same model as the first canvas. 
Made some minor css changes to make them look good. 
Made sure zooming effects both cameras. 
Introduced shaders for the other canvas as well.

2016-11-17 09:10 UTC, Rovanion commented
Till att börja med har vi test som inte passerar. Även om du inte har pre-commit-hooken installerad så kan du alltid köra `lein do cljfmt check, kibit` för att göra vad pre-commit-hooken gör.

2016-11-17 09:23 UTC, Rovanion requested changes
Programmet börjar läcka asmycket minne på den här branchen, ungefär 25MB i sekunden i Chrome. Vi kan inte merge:a den här koden innan det är åtgärdat.

Den producerar även varningen:

`[.Offscreen-For-WebGL-0x847276e0]RENDER WARNING: there is no texture bound to the unit 1`

vid varje frame vilket även det behöver åtgärdas.

2016-11-17 09:23 UTC, Rovanion commented on resources/public/css/style.css
> +#blur{
Eftersom du tog bort #main från den här regeln kan du slå samman denna regel med nedstående #blur-regel.

2016-11-28 07:05 UTC, hansfilipelo commented
Tested this branch on a Ubuntu 16.10-machine with Intel HD 4600 graphics and latest leiningen. This ate a CPU core and 2 GB RAM, then Chrome froze.

2016-11-28 17:11 UTC, Rovanion approved these changes

2016-11-28 18:10 UTC, merged