Turkey temp collection
WeatherMagic/weather-front pull request #30
Opened 2016-11-16 08:53 UTC by yotomten

It is now possible to fetch data from thor web server. To test this: 

- Run lein figwheel (ofc)
- Copy the full namespace (ns ..) code from core.cljs into the figwheel terminal
- write >> (io/request-example-temp-data)
Then you will se example data fetched from thor (printed)

then e.g.
- write >> (def climate-data (io/request-climate-data "temperature" [2 3 3] 1 4 37 42 2082 2082 6 12))
- and >> (go (println (<! climate-data)))

you will see the same data , but you requested it explicitly. 
 

You can request both with and without month limits, although the interpolation methods that will be used when month is omitted is not implemented yet (error message from thor). 

The input arguments to request-climate-data are given in the following order:

[dimension return-dim from-long to-long
    from-lat to-lat from-y to-y from-m to-m]

or

[dimension return-dim from-long to-long
    from-lat to-lat from-y to-y] ; No month limits

Last minute info from Hasse: (omitting month limits will be removed later on because of return-dimension solution)

2016-11-16 16:10 UTC, Rovanion requested changes

2016-11-16 16:10 UTC, Rovanion commented on src/weather_magic/core.cljs
> +   [cljs.core.async                :refer [<!]]))
Eftersom de ändra ändringarna gjorda till `core.cljs` är i namespace-deklarationen så borde även de ändringarna göras ogjorda.

2016-11-16 16:10 UTC, Rovanion commented on src/weather_magic/io.cljs
> +;; Requests example temperature data from thor webserver and prints it
Den här kommentaren ska läggas in i funktionens dokumentationstext istället. Detsamma går för alla andra kommentarer i den här filen.

2016-11-16 16:10 UTC, Rovanion commented on src/weather_magic/io.cljs
> +(defn request-example-temp-data
Den här funktionen borde implementeras genom ett kall till `request-climate-data` så att den är ett exempel på hur man använder funktionen du har skrivit.

2016-11-16 16:10 UTC, Rovanion commented on src/weather_magic/io.cljs
> +    from-lat to-lat from-y to-y from-m to-m]
Den här funktionen bör inte ta en lista av argument där argumentens position spelar roll utan den bör ta en map/dict av argument istället. Lite onödigt att man ger dig en lista som du sedan gör till en map när man bara kan räcka dig en map till att börja med.

2016-11-16 16:10 UTC, Rovanion commented on src/weather_magic/io.cljs
> +  ([dimension return-dim from-long to-long
Vad betyder den här och följande rad?

2016-11-17 17:41 UTC, yotomten commented on src/weather_magic/core.cljs
> +   [cljs.core.async                :refer [<!]]))
de ändra ändringarna?

2016-11-17 17:45 UTC, yotomten commented on src/weather_magic/core.cljs
> +   [cljs.core.async                :refer [<!]]))
Förstår icke vad du menar. Ska ja ta bort ändringarna för att det bara är namespace-ändringar? Eller ta bort för att de ändå finns i io.cljs ns:et och inte behövs i core?

2016-11-17 18:00 UTC, yotomten commented on src/weather_magic/io.cljs
> +  ([dimension return-dim from-long to-long
att man kan anropa funktionen med olika antal argument

2016-11-17 18:00 UTC, yotomten commented on src/weather_magic/io.cljs
> +    from-lat to-lat from-y to-y from-m to-m]
bra där!

2016-11-17 18:00 UTC, yotomten commented on src/weather_magic/io.cljs
> +(defn request-example-temp-data
absolut

2016-11-17 18:00 UTC, yotomten commented on src/weather_magic/io.cljs
> +;; Requests example temperature data from thor webserver and prints it
acknowledged!

2016-11-17 18:07 UTC, Rovanion commented on src/weather_magic/core.cljs
> +   [cljs.core.async                :refer [<!]]))
Eftersom att de enda ändringar som skett i core.cljs är dessa inkluderingar kan du omöjligen använda dem någonstans i core.cljs. Alltså bör du göra dessa ändringar ogjorda.

2016-11-17 18:09 UTC, Rovanion commented on src/weather_magic/io.cljs
> +  ([dimension return-dim from-long to-long
Jaja, nu är jag med! Såg inte att den var wrappad i en defn. Trodde du bara kallade en lista som en funktion mitt ute i ingenstans.

2016-11-19 08:24 UTC, yotomten commented
Fixed comments

2016-11-21 13:13 UTC, Rovanion approved these changes

2016-11-21 13:40 UTC, merged