Canvas lon lat
WeatherMagic/weather-front pull request #48
Opened 2016-11-24 09:35 UTC by owodunni

Ported two functions from python to clojure-script they enables us to go from model cordintes to lon lat coordinates.

2016-11-24 10:01 UTC, Rovanion commented
Det här kanske är en tyckessak men passar inte de här två funktionerna utomordentligt i util.cljs?

2016-11-24 10:03 UTC, owodunni commented
Jag har ingen aning. Jag vet inget om eran kod struktur.. Vill ni att det flyttas?

2016-11-24 10:07 UTC, Rovanion requested changes
Both functions seem to be possible to express in a [functionally pure](https://en.wikipedia.org/wiki/Pure_function) way since you never actually read from the atoms you modify.

Rewrite the two functions so that they do not depend on any external state, instead only rely on the arguments to produce a return value.

2016-11-24 10:14 UTC, owodunni commented
Hur returnar man något ur en funktion?

2016-11-24 10:17 UTC, Rovanion commented
Returvärdet ur en funktion är det sista som sägs i en funktion. Om du kör sudo apt-get install clojure så får du hem en terminal i vilken du kan leka runt lite. T.ex. kan du testa:

```
┌[rovanion][DrKleinersUbuntu]:~ 
└$ clojure
Clojure 1.6.0
user=> (defn f [a b] (+ a b))
#'user/f
user=> (f 1 2)
3
user=> (defn g [a b] (+ a b) (* a b))
#'user/g
user=> (g 1 2)
2
```

2016-11-24 10:18 UTC, owodunni commented
Fett! Jag flyttar till util och gör det till funktioner :8ball:

2016-11-24 10:40 UTC, Rovanion commented
Om du har flera värden i en funktion som du vill konstruera upp till ett enda returvärde på slutet är funktionen `let` som skapar ett lexikaliskt scope användbar:

```clojure
┌[rovanion][DrKleinersUbuntu]:~ 
└$ clojure
Clojure 1.6.0
user=> (defn g [a b] 
                     (let [sum (+ a b) 
                            times (* a b)] 
                      {:sum sum :times times}))
#'user/g
user=> (g 1 2)
{:sum 3, :times 2}
user=>
```

2016-11-28 19:34 UTC, owodunni commented
I messed up this branch, please review the lat-lon pr instead

2016-11-28 19:39 UTC, hansfilipelo commented
See PR #55 instead.

2016-11-28 19:39 UTC, closed without merging