Har lagt till två knappar som ändrar jordklotets rotation.
WeatherMagic/weather-front pull request #6
Opened 2016-10-03 13:36 UTC by MangeI89

2016-10-03 14:26 UTC, Rovanion commented
Den stora förändringen som behöver ske här är att allt gränssnittsrelaterat ska flyttas till `ui.cljs` där du lägger till ett kall till din komponent i `map-ui`.

2016-10-06 18:33 UTC, Rovanion requested changes
Annars ser det bara bra ut!

2016-10-06 18:33 UTC, Rovanion commented on src/weather_magic/core.cljs
> +
Modifieringarna till ovanstående rader kan du ogöra.

2016-10-06 18:33 UTC, Rovanion commented on src/weather_magic/state.cljs
> +(def earth-rotation (atom {:xAngle 24.5 :yAngle 0}))
De två ovan kan vi defonce:a.

2016-10-10 09:11 UTC, yotomten commented on src/weather_magic/world.cljs
> +(defn spin
Nu finns det en funktion som heter spin både i core och i state, är det bra?

2016-10-10 09:15 UTC, Rovanion commented on src/weather_magic/world.cljs
> +(defn spin
Nej den i core behöver få ett nytt namn eftersom den i.o.m. den här PR:en skulle ljuga om vad den gör då animaitonen numera är utbytbar. Den kan få heta t.ex. animate-earth.

2016-10-10 09:33 UTC, Rovanion approved these changes

2016-10-11 12:43 UTC, Rovanion commented
Här är det en rebase och en ändring av ett funktionsnamn som saknas från @MangeI89.

2016-10-13 09:43 UTC, closed without merging

2016-10-13 09:44 UTC, Rovanion commented
Superseeded by PR #15.