Made the buttons into balls
WeatherMagic/weather-front pull request #61
Opened 2016-11-30 09:22 UTC by Rovanion

Den här PR:en börjar med en normal css-normalisering som inte bara sätter alla kanter, marginaler och all stoppning till null.

Vidare gör den alla knappar till små runda bollar med regn som bakgrundsbild.

2016-11-30 10:06 UTC, majil334 submitted a review, later dismissed
Snyggt! Nu när master är mergad måste dock de högra knapparna (turkey, world osv) flyttas uppåt så man kan trycka på alla knappar. 

Man kan inte läsa texten på alla knappar heller, är väl bara "Temperature" som det spelar roll på iof!

2016-11-30 10:10 UTC, MangeI89 commented on resources/public/css/style.css
> -  box-shadow: 0 0 50px #255aaa;
Tycker att vi ska ha blå skugga (istället för svart) när man hovrar, annars får man ingen indikation att man kan klicka på knappen.

2016-11-30 10:14 UTC, MangeI89 requested changes
Tycker formen på knapparna var bättre innan, iaf för de som ligger högst upp. Tycker även att blå skugga blir bättre än svart, se enskild kommentar.

2016-12-05 13:58 UTC, Rovanion commented on resources/public/css/style.css
> -  box-shadow: 0 0 50px #255aaa;
Ordnat!

2016-12-05 23:58 UTC, Rovanion commented
Förhoppningsvis har alla era drömmar och förhoppningar, farhågor och orosmåln blivit besvarade i och med de senaste commitsen.

Jag får medge att standardknappen är ganska ful. Men kompassen, den ni, den är så vacker att man kan gråta.

2016-12-06 12:16 UTC, majil334 commented
Sjukt snygg kompass ja!! 👍 

Dock saknar jag att jorden snurrar i initialt läge. Knappen för detta också.

Såg att när man drar i time-slidern så snurras jorden dock, det är ju fel?

Personligen tycker jag att det vore nice med lite mer glow när man hovrar över knappar också :)

2016-12-06 17:36 UTC, Rovanion commented
@majil334 Fixade dina påpekanden. Tyvärr innebär det att dragningen avbryts när man drar musen över gränssnittselement.

2016-12-08 16:15 UTC, MangeI89 approved these changes

2016-12-08 16:16 UTC, merged