Use modified version of Geom to load CORS textures from thor
WeatherMagic/weather-front pull request #68
Opened 2016-12-04 17:29 UTC by Rovanion

The data is visible in the blend shader which it fucks up entirely.

Alternative titles: "CORSing through the galaxy", "The man who wouldn't stop lifting.", "Anomolous material 3 - Hey look it's the exact same thing as the last film" or "Silicon Valley - git gud son".

2016-12-04 18:08 UTC, hansfilipelo commented
I get white screen and errors in console (Chrome) when loading page: 

```
Uncaught TypeError: Cannot read property 'call' of undefined
    at Function.weather_magic.textures.load_data.cljs$core$IFn$_invoke$arity$variadic (http://localhost:3449/js/compiled/out/weather_magic/textures.js:137:132)
    at weather_magic$textures$load_data (http://localhost:3449/js/compiled/out/weather_magic/textures.js:128:41)
    at Function.weather_magic.textures.load_data_into_atom_and_return_key_BANG_.cljs$core$IFn$_invoke$arity$variadic (http://localhost:3449/js/compiled/out/weather_magic/textures.js:181:47)
    at weather_magic$textures$load_data_into_atom_and_return_key_BANG_ (http://localhost:3449/js/compiled/out/weather_magic/textures.js:173:72)
    at http://localhost:3449/js/compiled/out/weather_magic/state.js:81:239
-----------------------------
Uncaught Error: No protocol method ISwap.-swap! defined for type undefined: 
    at Object.cljs$core$missing_protocol [as missing_protocol] (http://localhost:3449/js/compiled/out/cljs/core.js:299:9)
    at Function.cljs.core._swap_BANG_.cljs$core$IFn$_invoke$arity$5 (http://localhost:3449/js/compiled/out/cljs/core.js:3063:17)
    at Function.cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$variadic (http://localhost:3449/js/compiled/out/cljs/core.js:15649:30)
    at cljs$core$swap_BANG_ (http://localhost:3449/js/compiled/out/cljs/core.js:15607:29)
    at weather_magic$transforms$update_model_coords (http://localhost:3449/js/compiled/out/weather_magic/transforms.js:52:29)
    at weather_magic$transforms$update_lat_lon (http://localhost:3449/js/compiled/out/weather_magic/transforms.js:58:46)
    at weather_magic$core$draw_frame_BANG_ (http://localhost:3449/js/compiled/out/weather_magic/core.js:79:41)
    at http://localhost:3449/js/compiled/out/weather_magic/core.js:102:37
    at thi$ng$geom$gl$webgl$animator$animate_STAR_ (http://localhost:3449/js/compiled/out/thi/ng/geom/gl/webgl/animator.js:90:23)
    at Function.thi.ng.geom.gl.webgl.animator.animate.cljs$core$IFn$_invoke$arity$2 (http://localhost:3449/js/compiled/out/thi/ng/geom/gl/webgl/animator.js:101:23)
    at thi$ng$geom$gl$webgl$animator$animate (http://localhost:3449/js/compiled/out/thi/ng/geom/gl/webgl/animator.js:72:46)
    at Function.thi.ng.geom.gl.webgl.animator.animate.cljs$core$IFn$_invoke$arity$1 (http://localhost:3449/js/compiled/out/thi/ng/geom/gl/webgl/animator.js:82:46)
    at thi$ng$geom$gl$webgl$animator$animate (http://localhost:3449/js/compiled/out/thi/ng/geom/gl/webgl/animator.js:68:46)
    at http://localhost:3449/js/compiled/out/weather_magic/core.js:101:68
```

2016-12-04 18:19 UTC, Rovanion commented
Well, that doesn't happen on my machine.

2016-12-05 07:52 UTC, yotomten commented
I get the same problems as hansfilip

2016-12-05 09:15 UTC, Rovanion commented
Do you get the issue with the code on branch hämta-riktig-data2?

2016-12-05 13:20 UTC, yotomten commented on src/weather_magic/shaders.cljs
> +     float temp = texture2D(trump, vUV).r * 3.0;
Texturen borde inte heta trump när trump inte längre används

2016-12-05 13:29 UTC, yotomten commented on src/weather_magic/textures.cljs
>    a reference to it along with an inticator as to whether the texture
indicator, not inticator

2016-12-05 13:31 UTC, yotomten commented on src/weather_magic/textures.cljs
> +  [texture-map gl-ctx & {:keys [variable request-params] :or {variable "temperature"}}]
why variable and not dimension?

2016-12-05 13:32 UTC, yotomten commented on src/weather_magic/textures.cljs
> +  (let [retval (load-data @texture-map-atom gl-ctx :variable variable :request-params request-params)]
retval or ret-val?

2016-12-05 13:33 UTC, yotomten commented on src/weather_magic/textures.cljs
> +  (def gl-ctx gl-ctx)
bort

2016-12-05 13:34 UTC, yotomten requested changes
Good job

2016-12-05 13:50 UTC, Rovanion commented on src/weather_magic/shaders.cljs
> +     float temp = texture2D(trump, vUV).r * 3.0;
Fixat.

2016-12-05 13:51 UTC, Rovanion commented on src/weather_magic/textures.cljs
>    a reference to it along with an inticator as to whether the texture
Done.

2016-12-05 13:52 UTC, Rovanion commented on src/weather_magic/textures.cljs
> +  [texture-map gl-ctx & {:keys [variable request-params] :or {variable "temperature"}}]
It's called variable on the back end.

2016-12-05 13:53 UTC, Rovanion commented on src/weather_magic/textures.cljs
> +  (let [retval (load-data @texture-map-atom gl-ctx :variable variable :request-params request-params)]
ret-val.

2016-12-05 13:53 UTC, Rovanion commented on src/weather_magic/textures.cljs
> +  (def gl-ctx gl-ctx)
Done.

2016-12-05 14:25 UTC, yotomten approved these changes

2016-12-05 14:25 UTC, merged