Time sliders on the bottom of the screen
WeatherMagic/weather-front pull request #7
Opened 2016-10-04 14:20 UTC by majil334

2016-10-05 12:49 UTC, yotomten commented on src/weather_magic/ui.cljs
> +  ;; TIME-SLIDER
No indent here. Is it supposed to be uppercase?

2016-10-05 12:50 UTC, yotomten commented on src/weather_magic/ui.cljs
> +(def date-atom (reagent/atom {:year {:value 2016 :min 1950 :max 2100} :month {:value 1 :min 1 :max 12}}))
Too long row?

2016-10-05 13:00 UTC, yotomten requested changes
See my comments in the code

2016-10-05 13:13 UTC, Rovanion requested changes

2016-10-05 13:13 UTC, Rovanion commented on resources/public/css/style.css
> +.time-slider{
Sätt in mellanrum mellan namn och måsvinge på denna och följande regler.

2016-10-05 13:13 UTC, Rovanion commented on src/weather_magic/ui.cljs
> +           :style {:width "100%"}
Stil skall stå i CSS, inte i HTML. Vi vill inte ha stilen uppdelad mellan både CSS och HTML-kod.

(I det här fallet så är blir ovanstående hiccup-syntax översatt till HTML när cljs-koden kör, men effekten är den samma.)

2016-10-05 13:13 UTC, Rovanion commented on src/weather_magic/ui.cljs
> +(def date-atom (reagent/atom {:year {:value 2016 :min 1950 :max 2100} :month {:value 1 :min 1 :max 12}}))
Eftersom vi i  `[reagent.core :as reagent :refer [atom]` ersätter ClojureScripts standardatom med den från reagent behöver du inte kvalificera `reagent/atom` med namnrymden `reagent` utan kan nöja dig med att endast skriva `atom`.

2016-10-05 13:13 UTC, Rovanion commented on src/weather_magic/ui.cljs
> +(defn slider [key value min max]
Blir koden verkligen mer läsbar av att ha en separat funktion `slider` som returnerar

```clojure
[:input {:type "range" :value value :min min :max max
         :on-change (fn [e] (swap! date-atom assoc-in [key :value] (.-target.value e)))}])
```

istället för att bara ha det rakt i `slider-componen`?

Här är inte svaret uppenbart och jag är nöjd oavsätt vilken väg du väljer.

2016-10-05 13:13 UTC, Rovanion commented on src/weather_magic/ui.cljs
> +      [:span {:style {:color "white"}} (name key) ": " (:value data)]
Släng in ett kall till `capitalize` på `(name key)` här så blir det stor bokstav också.

2016-10-06 10:16 UTC, Rovanion commented on src/weather_magic/ui.cljs
> +           :id "slider"
Nu skapar du flera element med samma id, det får inte ske för ett id ska vara unikt genom hela dokumentet. Ett alternativ är att ersätta `:id` med `:class` och i css:en selecta på `.slider` istället. Men även det känns lite rudundant för vad vi egentligen gör är att upprepa `<input type="range">` med ett annat ord, slider. 

Så vad jag föreslår är att du tar bort `:id "slider"` helt och i css:en använder selectorn `input[type=range]` när du vill referera till alla "sliders".

Annars bra jobbat, du hittade ju t.o.m. ett fel som vi andra inte såg!

2016-10-07 11:04 UTC, Rovanion approved these changes

2016-10-07 11:05 UTC, Rovanion commented
Nu är det bara @yotomten som har kvar att godkänna innan han får slå ihop detta med master.

2016-10-07 11:29 UTC, yotomten commented
Ska titta på det snarast! @Rovanion

2016-10-08 05:19 UTC, merged