both year and month time sliders now working
WeatherMagic/weather-front pull request #83
Opened 2016-12-08 10:08 UTC by majil334

Not pretty yet, this will be another task.

Had big trouble with merge, please look if something is missing or should not be there.

Test by play year (left button) and play month (right button)

2016-12-08 22:27 UTC, MangeI89 commented on src/weather_magic/core.cljs
> +  (draw-in-context state/gl-ctx-left @state/camera-left @state/background-camera-left @state/base-texture-left @state/textures-left state/shaders-left :left :year t)
Vi skickar alltid in :year som year-month-key. Kanske bra att ändra det beroende på play-mode eller?

2016-12-08 22:28 UTC, MangeI89 commented on src/weather_magic/core.cljs
> +      (swap! state/year-update assoc-in [left-right-key :month :time-of-last-update] (* 1 t)))))
Det bli mindre kod om du gör en funktion, tex update-year-month-info där year-month-key skickas in?

2016-12-08 22:29 UTC, MangeI89 requested changes
Se kommentarer :)

2016-12-09 07:32 UTC, majil334 commented on src/weather_magic/core.cljs
> +      (swap! state/year-update assoc-in [left-right-key :month :time-of-last-update] (* 1 t)))))
True, fixat!

2016-12-09 07:47 UTC, majil334 commented on src/weather_magic/core.cljs
> +  (draw-in-context state/gl-ctx-left @state/camera-left @state/background-camera-left @state/base-texture-left @state/textures-left state/shaders-left :left :year t)
Ja, det verkar det ju som.. men ärligt talat förstår jag inte riktigt vad parametrarna från year/month i draw-in-context gör?

2016-12-09 10:10 UTC, MangeI89 approved these changes

2016-12-09 10:11 UTC, merged