Stitching it all together
WeatherMagic/weather-front pull request #86
Opened 2016-12-08 14:42 UTC by Rovanion

Data is now loaded and placed correctly on the map when the play button is pressed.

The system currently locks up when Thor replies with an invalid image.

2016-12-08 17:32 UTC, yotomten commented
konflikter :D

2016-12-08 17:33 UTC, Rovanion commented
Allt löst!

2016-12-09 10:53 UTC, yotomten commented on src/weather_magic/core.cljs
>      (when (and @(:loaded base-texture) @(:loaded (:trump textures)))
Dags att skrota trump?

2016-12-09 10:55 UTC, yotomten commented on src/weather_magic/core.cljs
> +      ;; If the data from thor has been loaded, use that instead of trump.
Skrota trump snart?

2016-12-09 10:59 UTC, yotomten commented on src/weather_magic/core.cljs
>  (defn draw-frame! [t]
Enormous function ;)

2016-12-09 11:44 UTC, yotomten commented on src/weather_magic/textures.cljs
> +                    normally 'temperature' or 'percipitation'.
Why do you change from correct spelling to wrong spelling?

2016-12-09 12:02 UTC, yotomten requested changes
That's right

2016-12-09 12:02 UTC, yotomten commented on src/weather_magic/textures.cljs
> +                    normally 'temperature' or 'percipitation'.
http://tyda.se/search/precipitation?lang%5B0%5D=en&lang%5B1%5D=sv

2016-12-09 12:02 UTC, yotomten commented on src/weather_magic/textures.cljs
> +      (load-texture-if-needed gl-ctx "img/space5.jpg")))
We should change name on space5.jpg to space?

2016-12-09 13:04 UTC, Rovanion commented on src/weather_magic/core.cljs
> +      ;; If the data from thor has been loaded, use that instead of trump.
Vi vill ha någonting vi kan visa om Thor är nere, om vi bara har ingenting så kraschar programmet. Men det kan vara en god ide att byta ut bilden mot någon jätteliten bild som säger "Failed to load data". Skapar ett ärende på det #96.

2016-12-09 13:07 UTC, Rovanion commented on src/weather_magic/textures.cljs
> +                    normally 'temperature' or 'percipitation'.
Because git is hard.

2016-12-09 13:23 UTC, yotomten commented on src/weather_magic/core.cljs
> +      ;; If the data from thor has been loaded, use that instead of trump.
Affirmative

2016-12-09 13:23 UTC, yotomten approved these changes

2016-12-09 13:25 UTC, merged